name: CI

on: push

jobs:
  build_and_check:
    runs-on: ubuntu-latest
    container:
      image: theasp/clojurescript-nodejs:shadow-cljs-alpine
    steps:
      - uses: actions/checkout@v3

      - name: Download dependencies
        run: shadow-cljs npm-deps && npm install

      - name: Build app
        run: shadow-cljs compile app

      - name: Lint
        uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint src
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unit test
        run: |
          shadow-cljs compile test
          npm test

      - name: Integration test
        run: |
          shadow-cljs compile it-test
          npm run-script integration-test
